name: "CDK Deployment"

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  deployment:
    name: 'CDK DEPLOYMENT'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "AWS CDK Installation"
        run:  sudo npm i -g aws-cdk
      - name: "Install NPM Modules"
        run:  npm i
      - name: "AWS Creds"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::313327262346:role/Admin
          aws-region: us-east-1


