name: "CDK Deployment"

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  deployment:
    name: 'CDK DEPLOYMENT'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "sudo npm i -g aws-cdk"
        run: cdk synth
      - name: "cdk synth"
        run: cdk synth


